name: KumaDice
version: '${project.version}'
main: net.kumajunk.kumadice.KumaDice
api-version: 1.19

commands:
  kdice:
    description: diceroll
    usage: /kdice でhelpを確認

permissions:
  kdice.player:
    default: true
  kdice.op:
    default: op